### ISSUE TITLE
Separating flamecord.yml's MoTD into pre-1_16 (no hex/gradient support) and post-1_16 (hex/gradient support)

### ISSUE THREAD

**Issue by TheJoshue** [2lstudios-mc/FlameCord#185]
Adding new config options near `flamecord.yml` MoTD system (provided example of `flamecord.yml`'s part):
```yml
custom-motd:
  motd:
    pre-1_16:
      enabled: true
      motds:
      - |-
        &eDefault &cFlameCord&e sample!
        &eChange me in &cflamecord.yml&e file!
    post-1_16:
      enabled: false
      motd:
      - |-
        [Default](color=#ADF3FD format=italic) [FlameCord](color=#FF5C00-#F8FD06 format=bold) [sample](color=#ADF3FD format=italic)
        [Change me in](color=#ADF3FD format=italic) [flamecord.yml](color=#FF5C00-#F8FD06 format=bold) [file!](color=#ADF3FD format=italic)
  sample: # hover player count
    pre-1_16:
      enabled: true
      samples:
      - |-
        &eDefault &cFlameCord&e sample!
        &eChange me in &cflamecord.yml&e file!
    post-1_16:
      enabled: true
      samples:
      - |-
        [Default](color=#ADF3FD format=italic) [FlameCord](color=#FF5C00-#F8FD06 format=bold) [sample](color=#ADF3FD format=italic)
        [Change me in](color=#ADF3FD format=italic) [flamecord.yml](color=#FF5C00-#F8FD06 format=bold) [file!](color=#ADF3FD format=italic)
```
- If `pre-1_16` MoTD is **enabled** and `post-1_16` MoTDs is **not enabled**, then every client from 1.7 up to latest MC version will see the `pre-1_16` MoTD.
- If both `pre-1_16` and `post-1_16` MoTDs are **enabled** at the same time, then every 1.16+ (and higher) client will see `post-1_16` MoTD and every 1.15- (and lower) client will see `pre-1_16` MoTDs. This will ensure that if `post-1_16` is enabled, there will not be color translation so the both MoTDs will be in their own max potential.
- Making sure that `pre-1_16` only support regular colors (e.g. `&e`) and `post-1_16` support only hex/gradient (and not regular colors (e.g. `&e`))

__Sources to check__:
- For hex colors:
```java
class ColorsUtil {
private Pattern hexPattern = Pattern.compile("(#[a-fA-F0-9]{6})");

public static String hex(String message) {
        Matcher matcher = hexPattern.matcher(message);
        while (matcher.find()) {
            String hexCode = message.substring(matcher.start(), matcher.end());
            String replaceSharp = hexCode.replace('#', 'x');

            char[] ch = replaceSharp.toCharArray();
            StringBuilder builder = new StringBuilder("");
            for (char c : ch) {
                builder.append("&" + c);
            }

            message = message.replace(hexCode, builder.toString());
            matcher = hexPattern.matcher(message);
        }
        return ChatColor.translateAlternateColorCodes('&', message);
    }
}
```
- For gradients (used their formatting in the example above at `custom-motd.post-1_16`): https://github.com/Phoenix616/MineDown#syntax
- Alternative for gradients: https://github.com/Iridium-Development/IridiumColorAPI
