### ISSUE TITLE
Making any text/color (hex/gradient support potentially) for the proxy protocol name (overwriting player count)

### ISSUE THREAD

**Issue by TheJoshue** [2lstudios-mc/FlameCord#186]
Allowing full customizability for the proxy protocol (where the `{currentplayercount}/{maxplayercount}` is shown)

Example:
![image](https://user-images.githubusercontent.com/56804505/212540152-76475b0b-41d1-45f3-9f96-29cb1dc13c26.png)

`flamecord.yml` config part example:
```yml
  protocol:
    enabled: true
    name: "&a{currentplayercount}&7/&e{maxplayercount}"
```
another example for maintenance
```yml
  protocol:
    enabled: true
    name: "&c&oUnder Maintenance!"
```
potentially with gradient support mentioned at #185
