### ISSUE TITLE
BossBar dupe problem

### ISSUE THREAD

**Issue by OverBrave** [2lstudios-mc/FlameCord#59]
For some unknown reason, sometimes, but not always, "bossbars" accumulate when I teleport between servers and are fixed when I log out of the server completely. Is it a problem with Flamecord? Because there was no such problem before.

![image](https://user-images.githubusercontent.com/47111280/129443423-38ee00b3-6d8d-4e94-a5f6-e829cc862a5d.png)

I don't think it is due to the plugins used in normal servers. Because they multiply even when put with the vanilla bossbar command.

**Comment by andreasdc** [comment]
Show your flamecord config

**Comment by OverBrave** [comment]
```
logger:
  initialhandler: false
  exceptions: false
  dump: false
firewall:
  enabled: true
  notify: true
  seconds: 60
  names:
  - mcspam
```
