### ISSUE TITLE
Can't connect to main lobby on join.

### ISSUE THREAD

**Issue by QuartzWarrior** [2lstudios-mc/FlameCord#82]
Error on FlameCord server: `Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException`

Lobby Version: `CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`
FlameCord Version: `0.6.9`
Java Version Lobby: `8`
Java Version FlameCord: `11`

config.yml - proxy
```
server_connect_timeout: 5000
listeners:
- bind_local_address: true
  force_default_server: false
  forced_hosts:
    pvp.md-5.net: pvp
  host: 104.218.236.238:25565
  max_players: 1
  motd: '&1Another FlameCord server'
  ping_passthrough: false
  priorities:
  - lobby
  proxy_protocol: false
  query_enabled: false
  query_port: 25577
  tab_list: GLOBAL_PING
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  default:
  - bungeecord.command.server
  - bungeecord.command.list
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: true
timeout: 17000
player_limit: -1
ip_forward: true
groups:
  QuartzWarrior:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 53d7c7df-650b-4cde-aa54-89037524ba3d
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    address: 104.218.236.238:25566
    motd: '&1Just another FlameCord - Forced Host'
    restricted: false
```

server.properties - lobby
```
#Minecraft server properties
#Tue Jan 04 22:38:55 EST 2022
spawn-protection=16
query.port=25566
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=0
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
resource-pack-hash=
announce-player-achievements=true
pvp=true
snooper-enabled=true
level-type=DEFAULT
hardcore=false
enable-command-block=false
max-players=20
network-compression-threshold=256
max-world-size=29999984
server-port=25566
debug=false
server-ip=0.0.0.0
spawn-npcs=true
allow-flight=false
level-name=world
view-distance=10
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=false
max-build-height=256
level-seed=
use-native-transport=true
enable-rcon=false
motd=A Minecraft Server
```

spigot.yml - lobby
```
# This is the main configuration file for Spigot.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# For a reference for any variable inside this file, check out the Spigot wiki at
# http://www.spigotmc.org/wiki/spigot-configuration/
# 
# If you need help with the configuration or have any questions related to Spigot,
# join us at the IRC or drop by our forums and leave a post.
# 
# IRC: #spigot @ irc.spi.gt ( http://www.spigotmc.org/pages/irc/ )
# Forums: http://www.spigotmc.org/

config-version: 8
settings:
  save-user-cache-on-stop-only: false
  bungeecord: true
  late-bind: false
  sample-count: 12
  player-shuffle: 0
  filter-creative-items: true
  user-cache-size: 1000
  int-cache-limit: 1024
  moved-wrongly-threshold: 0.0625
  moved-too-quickly-threshold: 100.0
  timeout-time: 60
  restart-on-crash: true
  restart-script: ./start.sh
  netty-threads: 4
  attribute:
    maxHealth:
      max: 2048.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
  debug: false
timings:
  enabled: true
  verbose: true
  server-name-privacy: false
  hidden-config-entries:
  - database
  - settings.bungeecord-addresses
  history-interval: 300
  history-length: 3600
commands:
  tab-complete: 0
  log: true
  spam-exclusions:
  - /skill
  silent-commandblock-console: false
  replace-commands:
  - setblock
  - summon
  - testforblock
  - tellraw
messages:
  whitelist: You are not whitelisted on this server!
  unknown-command: Unknown command. Type "/help" for help.
  server-full: The server is full!
  outdated-client: Outdated client! Please use {0}
  outdated-server: Outdated server! I'm still on {0}
  restart: Server is restarting
stats:
  disable-saving: false
  forced-stats: {}
world-settings:
  default:
    verbose: true
    mob-spawn-range: 4
    anti-xray:
      enabled: true
      engine-mode: 1
      hide-blocks:
      - 14
      - 15
      - 16
      - 21
      - 48
      - 49
      - 54
      - 56
      - 73
      - 74
      - 82
      - 129
      - 130
      replace-blocks:
      - 1
      - 5
    nerf-spawner-mobs: false
    growth:
      cactus-modifier: 100
      cane-modifier: 100
      melon-modifier: 100
      mushroom-modifier: 100
      pumpkin-modifier: 100
      sapling-modifier: 100
      wheat-modifier: 100
      netherwart-modifier: 100
    entity-activation-range:
      animals: 32
      monsters: 32
      misc: 16
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
    ticks-per:
      hopper-transfer: 8
      hopper-check: 8
    hopper-amount: 1
    random-light-updates: false
    save-structure-info: true
    max-bulk-chunks: 10
    max-entity-collisions: 8
    dragon-death-sound-radius: 0
    seed-village: 10387312
    seed-feature: 14357617
    hunger:
      walk-exhaustion: 0.2
      sprint-exhaustion: 0.8
      combat-exhaustion: 0.3
      regen-exhaustion: 3.0
    max-tnt-per-tick: 100
    max-tick-time:
      tile: 50
      entity: 50
    item-despawn-rate: 6000
    merge-radius:
      item: 2.5
      exp: 3.0
    arrow-despawn-rate: 1200
    enable-zombie-pigmen-portal-spawns: true
    view-distance: 10
    wither-spawn-sound-radius: 0
    hanging-tick-frequency: 100
    zombie-aggressive-towards-villager: true
    chunks-per-tick: 650
    clear-tick-list: false
```

paper.yml - lobby
```
# This is the main configuration file for PaperSpigot.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to PaperSpigot,
# join us at the IRC.
# 
# IRC: #paperspigot @ irc.spi.gt ( http://irc.spi.gt/iris/?channels=PaperSpigot )

config-version: 9
settings:
  baby-zombie-movement-speed: 0.5
  limit-player-interactions: true
data-value-allowed-items: []
stackable-buckets:
  lava: false
  water: false
  milk: false
warnWhenSettingExcessiveVelocity: true
effect-modifiers:
  strength: 1.3
  weakness: -0.5
world-settings:
  default:
    verbose: true
    generator-settings:
      canyon: true
      caves: true
      dungeon: true
      fortress: true
      mineshaft: true
      monument: true
      stronghold: true
      temple: true
      village: true
      flat-bedrock: false
    allow-block-location-tab-completion: true
    disable-teleportation-suffocation-check: false
    optimize-explosions: false
    falling-block-height-nerf: 0
    max-growth-height:
      cactus: 3
      reeds: 3
    remove-unloaded:
      enderpearls: true
      tnt-entities: true
      falling-blocks: true
    load-chunks:
      enderpearls: false
      tnt-entities: false
      falling-blocks: false
    game-mechanics:
      boats-drop-boats: false
      disable-player-crits: false
      disable-chest-cat-detection: false
      disable-end-credits: false
    tnt-explosion-volume: 4.0
    mob-spawner-tick-rate: 1
    player-blocking-damage-multiplier: 0.5
    remove-invalid-mob-spawner-tile-entities: true
    nether-ceiling-void-damage: false
    fast-drain:
      lava: false
      water: false
    lava-flow-speed:
      normal: 30
      nether: 10
    squid-spawn-height:
      minimum: 45.0
      maximum: 63.0
    cache-chunk-maps: false
    player-exhaustion:
      block-break: 0.02500000037252903
      swimming: 0.014999999664723873
    despawn-ranges:
      soft: 32
      hard: 128
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 900
    disable-explosion-knockback: false
    water-over-lava-flow-speed: 5
    fix-cannons: false
    tnt-entity-height-nerf: 0
    use-hopper-check: false
    all-chunks-are-slime-chunks: false
    allow-undead-horse-leashing: false
    keep-spawn-loaded: true
    falling-blocks-collide-with-signs: false
    container-update-tick-rate: 1
    portal-search-radius: 128
    disable-thunder: false
    disable-ice-and-snow: false
    tick-next-tick-list-cap: 10000
    tick-next-tick-list-cap-ignores-redstone: false
    disable-mood-sounds: false
    use-async-lighting: false
```

bukkit.yml - lobby
```
# This is the main configuration file for Bukkit.
# As you can see, there's actually not that much to configure without any plugins.
# For a reference for any variable inside this file, check out the Bukkit Wiki at
# http://wiki.bukkit.org/Bukkit.yml
# 
# If you need help on this file, feel free to join us on irc or leave a message
# on the forums asking for advice.
# 
# IRC: #spigot @ irc.spi.gt
#    (If this means nothing to you, just go to http://www.spigotmc.org/pages/irc/ )
# Forums: http://www.spigotmc.org/
# Bug tracker: http://www.spigotmc.org/go/bugs


settings:
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: -1
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server closed
spawn-limits:
  monsters: 70
  animals: 15
  water-animals: 5
  ambient: 15
chunk-gc:
  period-in-ticks: 600
  load-threshold: 0
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  autosave: 6000
aliases: now-in-commands.yml
database:
  username: bukkit
  isolation: SERIALIZABLE
  driver: org.sqlite.JDBC
  password: walrus
  url: jdbc:sqlite:{DIR}{NAME}.db
```
